name: Run Fear and Greed Index Daily

on:
  schedule:
    - cron: '0 5 * * *'  # 7 AM Europe/Rome (UTC+2 during daylight saving)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install pandas numpy matplotlib requests

      - name: Run script
        run: |
          python Fear\ Greed\ Script.py
